# infra/nginx/conf.d.local/meogeuljido.local.conf
server {
    listen 443 ssl;
    http2 on;
    server_name local.meogeuljido.dev localhost;

    ssl_certificate     /etc/nginx/certs-local/fullchain.pem;
    ssl_certificate_key /etc/nginx/certs-local/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;

    root /usr/share/nginx/html;
    index index.html;

    include /etc/nginx/snippets/_common.locations.conf;

    location /uploads/ {
        alias /usr/share/nginx/uploads/;
    }

}
